### ISSUE TITLE
Data is available in Github, but link is broken

### ISSUE THREAD

**Issue by Laurent-Smeets-GSS-Account** [InseeFrLab/lockdown-maps-R#14]
This link to the data works: https://github.com/InseeFrLab/lockdown-maps-R/blob/master/data/MouvementsPopulation_confinement2020.csv. However the link in the readme ([Dataviz Data](insee.fr/fr/statistiques/fichier/5350073/mouvements_population_confinement_2020_csv.zip), as published in April 2021: allows re-use by disseminating flows, is broken.

**Comment by milena-git** [comment]
Thank you for reporting this. Hopefully it will be settled today as we are waiting for the dataset released on insee.fr which is bit late.

**Comment by RLesur** [comment]
It seems that the link works now. I close this issue. Feel free to re-open.
