### ISSUE TITLE
donutmaps

### ISSUE THREAD

**Issue by mtennekes** [InseeFrLab/lockdown-maps-R#15]
I created a new and public R package: https://github.com/mtennekes/donutmaps

* It (only) contains the function `back_donuts`.
* One change w.r.t. the old function (that is also included in this repo): I've added the parameter `var`, which contains the variable name of flow values. In the old case (and in your case), it should be `"flow"`

@milena-git The old private repo `donut_maps` still exists, but I'll have to remove bake_donuts there as well, and probably rename this repo.

**Comment by milena-git** [comment]
Hi Martijn, cool for the new R package. I changed to depend on this package instead of the `R/bake_donuts.R` which I deleted. For the old private repo, feel free to make any change
