### ISSUE TITLE
Spreadsheet moved on insee website?

### ISSUE THREAD

**Issue by RLesur** [InseeFrLab/lockdown-maps-R#16]
This link to `TCRD_021.xls` file seems to be broken
https://github.com/InseeFrLab/lockdown-maps-R/blob/4835083e9e74e24f80b8b96e2b86b477a99aa0fd/R/maps_utils.R#L20

**Comment by milena-git** [comment]
The link https://www.insee.fr/fr/statistiques/fichier/2012692/TCRD_021.xls (population estimates for 2020) was 'updated' to https://www.insee.fr/fr/statistiques/fichier/2012692/TCRD_021.xlsx (population estimates for 2021), the previous link being broken. Guessing that it could happen again, I uploaded the data in the repo instead. 

insee.fr was not working for a few days, so the viz could not be built (we still fetch population mouvement estimes on insee.fr)

Now we have another issue on installing dependencies, possibly related to the release of `sf` package new version two days ago (2021-06-09) and its relationship with tmap

`* installing *source* package ‘sf’ ...
** package ‘sf’ successfully unpacked and MD5 sums checked
** using staged installation
configure: CC: clang -mmacosx-version-min=10.13
configure: CXX: clang++ -mmacosx-version-min=10.13 -std=gnu++11
configure: error: gdal-config not found or not executable.
checking for gdal-config... no
no
ERROR: configuration failed for package ‘sf’
* removing ‘/Users/runner/work/_temp/Library/sf’

The downloaded source packages are in
	‘/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpXfNlbe/downloaded_packages’
Running `R CMD build`...
* checking for file ‘/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpXfNlbe/remotes5ce3f81ee11/mtennekes-tmap-e882b60/DESCRIPTION’ ... OK
* preparing ‘tmap’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
      -----------------------------------
ERROR: dependency ‘sf’ is not available for package ‘tmap’
* removing ‘/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp43u6qi/Rinste224e1369f0/tmap’
      -----------------------------------
ERROR: package installation failed
STDOUT:
* checking for file ‘/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpXfNlbe/remotes5ce3f81ee11/mtennekes-tmap-e882b60/DESCRIPTION’ ... OK
* preparing ‘tmap’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
      -----------------------------------
ERROR: dependency ‘sf’ is not available for package ‘tmap’
* removing ‘/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp43u6qi/Rinste224e1369f0/tmap’
      -----------------------------------
ERROR: package installation failed
STDERR:

Error: Error: Failed to install 'tmap' from GitHub:
  Failed to `R CMD build` package, try `build = FALSE`.
In addition: Warning messages:
1: In i.p(...) : installation of package ‘sf’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T//RtmpXfNlbe/file5ce10467635/odf_0.1.0.tar.gz’ had non-zero exit status
3: In i.p(...) : installation of package ‘sf’ had non-zero exit status
Execution halted
Error: Process completed with exit code 1.`

**Comment by milena-git** [comment]
Updating dependencies of `odf` was enough to deal with the later
